ClientApplicationMVC/Controllers/CompanyListingsController.cs
using ClientApplicationMVC.Models;

using Messages.DataTypes.Database.CompanyDirectory;
using Messages.ServiceBusRequest.CompanyDirectory.Responses;
using Messages.ServiceBusRequest.CompanyDirectory.Requests;

using System;
using System.Web.Mvc;
using System.Web.Routing;
using Messages.ServiceBusRequest.ReviewService.Requests;
using Messages.ServiceBusRequest.ReviewService.Responses;
using Messages.DataTypes.Database.ReviewService;
using Messages.ServiceBusRequest;
using Messages.ServiceBusRequest.WeatherService.Requests;
using Messages.ServiceBusRequest.WeatherService.Responses;

namespace ClientApplicationMVC.Controllers
{
    /// <summary>
    /// This class contains the functions responsible for handling requests routed to *Hostname*/CompanyListings/*
    /// </summary>
    public class CompanyListingsController : Controller
    {
        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings
        /// </summary>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult Index()
        {
            if (Globals.isLoggedIn())
            {
                ViewBag.Companylist = null;
                return View("Index");
            }
            return RedirectToAction("Index", "Authentication");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/Search
        /// </summary>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult Search(string textCompanyName)
        {

            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if(connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            CompanySearchRequest request = new CompanySearchRequest(textCompanyName);

            CompanySearchResponse response = connection.searchCompanyByName(request);
            if (response.result == false)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.Companylist = response.list;

            return View("Index");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/DisplayCompany/*info*
        /// </summary>
        /// <param name="id">The name of the company whos info is to be displayed</param>
        /// <returns>A view to be sent to the client</returns>
        public ActionResult DisplayCompany(string id)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if ("".Equals(id))
            {
                return View("Index");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            ViewBag.CompanyName = id;
            
            GetCompanyInfoRequest infoRequest = new GetCompanyInfoRequest(new CompanyInstance(id));
            GetCompanyInfoResponse infoResponse = connection.getCompanyInfo(infoRequest);
            ViewBag.CompanyInfo = infoResponse.companyInfo;

            GetCompanyReviewsRequest reviewRequest = new GetCompanyReviewsRequest(id);
            GetCompanyReviewsResponse reviewResponse = connection.getCompanyReviews(reviewRequest);


            /* Making the weather request to get the key for the address of the first location */
            GetCityKeyRequest keyRequest = new GetCityKeyRequest(infoResponse.companyInfo.locations[0]);
            ServiceBusResponse keyResponse = connection.getCityKey(keyRequest);

            /* Making the weather request to get current conditions of the key extracted above */
            if(keyResponse.result)
            {
                //Key extracted, make the call for the current conditions
                GetWeatherRequest weatherRequest = new GetWeatherRequest(keyResponse.response);
                GetWeatherResponse weatherResponse = connection.getWeather(weatherRequest);
                if (weatherResponse.result)
                {
                    //Weather response successfully received
                    ViewBag.WeatherIcon = "~/Content/Images/" + weatherResponse.Weather.WeatherIcon + ".png";
                    ViewBag.WeatherText = weatherResponse.Weather.WeatherText;
                    ViewBag.City = infoResponse.companyInfo.locations[0];
                    ViewBag.Temp = weatherResponse.Weather.Temperature.Metric.Value;
                    ViewBag.RealFeel = weatherResponse.Weather.RealFeelTemperature.Metric.Value;
                }
                else
                {
                    //Weather response not received
                    ViewBag.City = "Could not pull the weather.";
                }
            }
            else
            {
                //No key was found, so don't make this call
                ViewBag.City = "City not found.";
            }


            foreach (ReviewInstance review in reviewResponse.List.List)
            {
                int timestamp = (int.Parse(review.TimeStamp));
                DateTime dt = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(timestamp).ToLocalTime();
                string formattedDate = dt.ToString("hh:mm tt dd/MM/yyyy");
                review.TimeStamp = formattedDate;
            }

            ViewBag.Reviews = reviewResponse.List.List.ToArray();
            ViewBag.username = Globals.getUser();
            return View("DisplayCompany");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/ReviewCompany/*info*
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ReviewCompany(string id)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if ("".Equals(id))
            {
                return View("Index");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }
            ViewBag.stars = 5;
            ViewBag.CompanyName = id;
            return View("WriteReview");
        }

        /// <summary>
        /// This function is called when the client navigates to *hostname*/CompanyListings/ReviewCompany/*info*
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult PublishReview(string companyName, string reviewContent, int stars)
        {
            if (Globals.isLoggedIn() == false)
            {
                return RedirectToAction("Index", "Authentication");
            }
            if ("".Equals(reviewContent))
            {
                ViewBag.CompanyName = companyName;
                ViewBag.Error = "*Please Enter a Description of Your Review";
                return View("WriteReview");
            }
            if ("".Equals(companyName) || "".Equals(stars))
            {
                return View("Index");
            }

            ServiceBusConnection connection = ConnectionManager.getConnectionObject(Globals.getUser());
            if (connection == null)
            {
                return RedirectToAction("Index", "Authentication");
            }

            long time = DateTimeOffset.Now.ToUnixTimeSeconds();
            string username = Globals.getUser();
            ReviewInstance review = new ReviewInstance(companyName, reviewContent, stars, time.ToString(), username);
            SaveCompanyReviewRequest saveRequest = new SaveCompanyReviewRequest(review);
            ServiceBusResponse response = connection.saveCompanyReview(saveRequest);
            ViewBag.companyName = companyName;
            ViewBag.Response = response.response;
            return View("WriteReview");
        }
    }
}

ClientApplicationMVC/Views/CompanyListings/DisplayCompany.cshtml
<link href="~/Content/ChatStyles.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="~/Scripts/CompanyListings/CompanyListingsFunctions.js"></script>

<hr/>
<div class="row">
    <div class="col-md-6">
        <h2 id="CompanyNameDisplay">@ViewBag.CompanyName</h2>
    </div>
    <div class="col-md-2 text-center" style="background-color:whitesmoke; vertical-align: top; min-height: 170px">
        <h4 style="color:maroon">@ViewBag.City</h4>
        @if (ViewBag.Temp != null)
        {
            <h3>@ViewBag.Temp  &#8451;</h3>
        }
        <h4>@ViewBag.WeatherText</h4>
        <p>Real Feel: @ViewBag.RealFeel &#8451; </p>

</div>
    <div class="col-md-1 text-left" style="background-color:whitesmoke; vertical-align: top; min-height: 170px">
        <br />
        <br />
        @if (ViewBag.WeatherText != null)
        {
            <img src="@Url.Content(ViewBag.WeatherIcon)" alt="Image"/>
        }
    </div>

</div>
<div class="hidden" id="companyUserName">@ViewBag.CompanyInfo.userName</div>
<hr />


<textarea id="username_title" disabled hidden>@ViewBag.username</textarea>

<div class="row">
    <div class="col-md-2">
        <b style="font-size:15px">Email:</b>
    </div>
    <div class="col-md-2">
        <span style="font-size: 15px;">@ViewBag.CompanyInfo.email</span>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-2">
        <b style="font-size:15px">Phone Number:</b>
    </div>
    <div class="col-md-1">
        <span style="font-size: 15px;">@ViewBag.CompanyInfo.phoneNumber</span>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <b style="font-size:15px">@ViewBag.CompanyName can be found at these locations:</b>
    </div>
</div>
<br />

@foreach (string location in ViewBag.CompanyInfo.locations)
{
    <div class="row">
        <div class="col-md-8 col-md-offset-1"> &#9679 @location</div>
    </div>
}
<hr />


<h3>@ViewBag.CompanyName's Reviews</h3>
<div style="height:400px; border-style:outset; overflow-y: scroll; overflow-x:hidden; padding-left:1em; padding-right:1em;">
    <br />
    @foreach (var review in ViewBag.Reviews)
    {
        <div style="border-radius:5px; box-shadow:2px 2px 2px 2px black; background-color:gainsboro;">
            <p style="padding-left:1em; font-size:16px;">@(review.UserName)</p>
            <p style="padding-left:2em;">stars: @(review.Stars)</p>
            <p style="padding-left:2em;">description: @(review.Review)</p>
            <p style="padding-left:2em;">@(review.TimeStamp)</p>
        </div>
        <br />
    }
</div>

<br />
<input class="btn btn-default" type="button" value="Write Review" onclick="location.href='@Url.Action("ReviewCompany", "CompanyListings",  new { id = ViewBag.CompanyName } )'" />
<hr />

<br />
<h3>Start a conversation with @ViewBag.CompanyName</h3>

<div float:left">
    <textarea style="height:100px; width:500px;" class="messagetextarea" id="textUserMessage" placeholder="Enter your message here."></textarea>
</div>

<br />

<button class="btn btn-default" id="SendMessageButton">Send</button>

<hr />
<br />

@* SignalR and JS Scripts *@
@section scripts{
    <script type="text/javascript" src="~/Scripts/Chat/ChatFunctions.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script type="text/javascript" src="~/signalr/hubs"></script>
}

ClientApplicationMVC/Views/CompanyListings/Index.cshtml
<!--
    This page will be used to search for and display Company names
-->
@{
    ViewBag.Title = "Index";
}

<script type="text/javascript" src="~/Scripts/ReviewService/ReviewService.js"></script>

<h2>Search for companies by name</h2>
<style>
    input[type=text], select {
        border-radius: 4px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        padding: 6px;
        width: 250px;
    }
</style>


@using (Html.BeginForm("Search", "CompanyListings", FormMethod.Get, new { id = "searchForm", onsubmit = "return validateSearch()" }))
{
    <p>@ViewBag.Message</p>
    <br />

    @Html.TextBox("textCompanyName", null, new { id = "searchTextBox" })
    <input type="submit" value="Search" class="btn btn-default" />
    <br /><br /><br />


}

@if (ViewBag.Companylist != null)
{
    if (ViewBag.Companylist.companyNames.Length == 0)
    {
        <div id="searchResult" style="color:#FF0000">Your search did not retrun any results. Please try again.</div>
    }
    else
    {
        <h3>Results:</h3>
        <br />
        foreach (string item in ViewBag.Companylist.companyNames)
        {
            @Html.ActionLink(item, "DisplayCompany", "CompanyListings", new { id = item}, null)
            <br />
        }
    }
}

<div id="searchError" style="color:#FF0000"></div>

ClientApplicationMVC/Views/CompanyListings/WriteReview.cshtml
@{
    ViewBag.Title = "Write Review";
}
<script type="text/javascript" src="~/Scripts/ReviewService/ReviewService.js"></script>

<style>
    input[type=select], select {
        border-radius: 4px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        padding: 6px;
        width: 80px;
    }
</style>

<h2>Write a Review for @ViewBag.CompanyName</h2>
<hr />


<form id="reviewForm" action="/CompanyListings/PublishReview" onsubmit="return validateReview()">
    <div class="row">
        <div class="col-md-10">
            <textarea id="reviewTextBox" style="width:450px; height:200px" name="reviewContent" value="@ViewBag.reviewText" placeholder="Enter your review here" rows="3"></textarea>
            <p style="font-size:16px; color:red">@ViewBag.Error</p>
        </div>
    </div>
    <br />
    <div class="row">
        <div style="float:left" class="col-md-1">
            <select id="selector" ; name="stars">
                <option value="5">5 Stars</option>
                <option value="4">4 Stars</option>
                <option value="3">3 Stars</option>
                <option value="2">2 Stars</option>
                <option value="1">1 Star</option>
            </select>
        </div>
    </div>
    <br />
    <div class="row">
        <div style="float:left" class="col-md-1">
            <input type="hidden" name="companyName" value="@ViewBag.CompanyName">
            <input class="btn btn-default" type="submit" value="Publish" />
        </div>
    </div>
</form>

<div id="reviewError" style="color:#FF0000"></div>

<p style="font-size:20px;">@ViewBag.Response</p>
<br />